const chapters = [
  { num: 1, title: "1일차", sub: "D-30", file: "chapters/ch1.html" },
  { num: 2, title: "2일차", sub: "D-29", file: "chapters/ch2.html" },
  { num: 3, title: "3일차", sub: "D-28", file: "chapters/ch3.html" },
  { num: "외전", title: "GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night.html" },
  { num: 4, title: "4일차", sub: "D-27", file: "chapters/ch4.html" },
  { num: 5, title: "5일차", sub: "D-26", file: "chapters/ch5.html" },
  { num: 6, title: "6일차", sub: "D-25", file: "chapters/ch6.html" },
  { num: 7, title: "7일차", sub: "D-24", file: "chapters/ch7.html" },
  { num: 8, title: "8일차", sub: "D-23", file: "chapters/ch8.html" },
  { num: 9, title: "9일차", sub: "D-22", file: "chapters/ch9.html" },
  { num: "외전2", title: "9일차 GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night2.html" },
  { num: 10, title: "10일차", sub: "D-21", file: "chapters/ch10.html" },
  { num: 11, title: "11일차", sub: "D-20", file: "chapters/ch11.html" },
  { num: 12, title: "12일차", sub: "D-19", file: "chapters/ch12.html" },
  { num: 13, title: "13일차", sub: "D-18", file: "chapters/ch13.html" },
  { num: "외전3", title: "13일차 GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night3.html" },
  { num: 14, title: "14일차", sub: "D-17", file: "chapters/ch14.html" },
  { num: 15, title: "15일차", sub: "D-16", file: "chapters/ch15.html" },
  { num: 16, title: "16일차", sub: "D-15", file: "chapters/ch16.html" },
  { num: 17, title: "17일차", sub: "D-14", file: "chapters/ch17.html" },
  { num: 18, title: "18일차", sub: "D-13", file: "chapters/ch18.html" },
  { num: 19, title: "19일차", sub: "D-12", file: "chapters/ch19.html" },
  { num: 20, title: "20일차", sub: "D-11", file: "chapters/ch20.html" },
  { num: 21, title: "21일차", sub: "D-10", file: "chapters/ch21.html" },
  { num: 22, title: "22일차", sub: "D-9", file: "chapters/ch22.html" },
  { num: 23, title: "23일차", sub: "D-8", file: "chapters/ch23.html" },
  { num: 24, title: "24일차", sub: "D-7", file: "chapters/ch24.html" },
  { num: 25, title: "25일차", sub: "D-6", file: "chapters/ch25.html" },
  { num: 26, title: "26일차", sub: "D-5", file: "chapters/ch26.html" },
  { num: 27, title: "27일차", sub: "D-4", file: "chapters/ch27.html" },
  { num: 28, title: "28일차", sub: "D-3", file: "chapters/ch28.html" },
  { num: 29, title: "29일차", sub: "D-2", file: "chapters/ch29.html" },
  { num: 30, title: "30일차", sub: "D-1", file: "chapters/ch30.html" },
  { num: 31, title: "31일차", sub: "D-0", file: "chapters/ch31.html" },
  { num: 32, title: "32일차", sub: "D+1", file: "chapters/ch32.html" },
  { num: 33, title: "33일차", sub: "D+2", file: "chapters/ch33.html" },
  { num: 34, title: "34일차", sub: "D+3", file: "chapters/ch34.html" },
  { num: 35, title: "35일차", sub: "D+4", file: "chapters/ch35.html" },
  { num: 36, title: "36일차", sub: "D+5", file: "chapters/ch36.html" },
  { num: 37, title: "37일차", sub: "D+6", file: "chapters/ch37.html" },
  { num: 38, title: "38일차", sub: "D+7", file: "chapters/ch38.html" },
  { num: 39, title: "39일차", sub: "D+8", file: "chapters/ch39.html" },
  { num: 40, title: "40일차", sub: "D+9", file: "chapters/ch40.html" },
  { num: 41, title: "41일차", sub: "D+10", file: "chapters/ch41.html" },
  { num: 42, title: "42일차", sub: "D+11", file: "chapters/ch42.html" },
  { num: 43, title: "43일차", sub: "D+12", file: "chapters/ch43.html" },
];
