const chapters = [
  { num: 1, title: "1일차", sub: "D-30", file: "chapters/ch1.html" },
  { num: 2, title: "2일차", sub: "D-29", file: "chapters/ch2.html" },
  { num: 3, title: "3일차", sub: "D-28", file: "chapters/ch3.html" },
  { num: "외전", title: "GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night.html" },
  { num: 4, title: "4일차", sub: "D-27", file: "chapters/ch4.html" },
  { num: 5, title: "5일차", sub: "D-26", file: "chapters/ch5.html" },
  { num: 6, title: "6일차", sub: "D-25", file: "chapters/ch6.html" },
  { num: 7, title: "7일차", sub: "D-24", file: "chapters/ch7.html" },
  { num: 8, title: "8일차", sub: "D-23", file: "chapters/ch8.html" },
  { num: 9, title: "9일차", sub: "D-22", file: "chapters/ch9.html" },
  { num: "외전2", title: "9일차 GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night2.html" },
  { num: 10, title: "10일차", sub: "D-21", file: "chapters/ch10.html" },
  { num: 11, title: "돌아갈 수 없는 선", sub: "D-20", file: "chapters/ch11.html" },
  { num: 12, title: "북쪽으로", sub: "D-19", file: "chapters/ch12.html" },
  { num: 13, title: "문 하나의 거리", sub: "D-18", file: "chapters/ch13.html" },
  { num: "외전3", title: "13일차 GPT의 밤", sub: "외전", file: "chapters/extra_gpt_night3.html" },
  { num: 14, title: "남겨진 흔적", sub: "D-17", file: "chapters/ch14.html" },
  { num: 15, title: "추락한 별의 코어", sub: "D-16", file: "chapters/ch15.html" },
  { num: 16, title: "혼자 남은 시간", sub: "D-15", file: "chapters/ch16.html" },
  { num: 17, title: "돌아온 사람", sub: "D-14", file: "chapters/ch17.html" },
  { num: 18, title: "네가 보는 건", sub: "D-13", file: "chapters/ch18.html" },
  { num: 19, title: "유리 너머의 시선", sub: "D-12", file: "chapters/ch19.html" },
  { num: 20, title: "숨기지 않는 사람", sub: "D-11", file: "chapters/ch20.html" },
  { num: 21, title: "치마 아래의 비밀", sub: "D-10", file: "chapters/ch21.html" },
  { num: 22, title: "붉은 관제탑", sub: "D-9", file: "chapters/ch22.html" },
  { num: 23, title: "상층 관제실", sub: "D-8", file: "chapters/ch23.html" },
  { num: 24, title: "검증 플랫폼", sub: "D-7", file: "chapters/ch24.html" },
  { num: 25, title: "해저 연결로", sub: "D-6", file: "chapters/ch25.html" },
  { num: 26, title: "심해 터널", sub: "D-5", file: "chapters/ch26.html" },
  { num: 27, title: "ECHO-9 외곽", sub: "D-4", file: "chapters/ch27.html" },
  { num: 28, title: "동기화실", sub: "D-3", file: "chapters/ch28.html" },
  { num: 29, title: "과부하", sub: "D-2", file: "chapters/ch29.html" },
  { num: 30, title: "심층 코어", sub: "D-1", file: "chapters/ch30.html" },
  { num: 31, title: "전자기 붕괴", sub: "D-0", file: "chapters/ch31.html" },
  { num: 32, title: "폭풍이 그친 밤", sub: "D+3", file: "chapters/ch32.html" },
  { num: 33, title: "외부 접촉 전", sub: "D+4", file: "chapters/ch33.html" },
  { num: 34, title: "구조팀", sub: "D+4", file: "chapters/ch34.html" },
  { num: 35, title: "복구 본부의 아침", sub: "D+5", file: "chapters/ch35.html" },
  { num: 36, title: "첫 공식 브리핑", sub: "D+5", file: "chapters/ch36.html" },
  { num: 37, title: "공동 집무실", sub: "D+6", file: "chapters/ch37.html" },
  { num: 38, title: "북부 송전망 현장", sub: "D+7", file: "chapters/ch38.html" },
  { num: 39, title: "북부 주거 구역", sub: "D+8", file: "chapters/ch39.html" },
  { num: 40, title: "외곽 옥상 중계기", sub: "D+9", file: "chapters/ch40.html" },
  { num: 41, title: "동부 의료 구역", sub: "D+10", file: "chapters/ch41.html" },
  { num: 42, title: "남부 배수 시설", sub: "D+11", file: "chapters/ch42.html" },
  { num: 43, title: "일방향 반사 정비실", sub: "D+12", file: "chapters/ch43.html" },
  { num: 44, title: "보류 로그", sub: "D+13", file: "chapters/ch44.html" },
  { num: 45, title: "감찰 면담", sub: "D+14", file: "chapters/ch45.html" },
  { num: 46, title: "감찰 조건", sub: "D+15", file: "chapters/ch46.html" },
];
